### ISSUE TITLE
Fix incompatibility with iTerm2 3.0 beta

### ISSUE THREAD

**Issue by muhqu** [muhqu/dterm#8]
As filed over here: https://github.com/bdrister/dterm/issues/4
> I upgraded to from iTerm2 2.x to 3.0. dTerm silently fails to open a terminal window now. But this is in the logs:
> `6/8/16 6:45:48.825 PM DTerm[526]: Can't find app with identifier net.sourceforge.iTerm`
> `6/8/16 6:45:48.834 PM DTerm[526]: warning: <ITermApplication @0x40015bce0: application "iTerm" (309)> has no class for scripting class "terminal". `

Thanks @aberezin for reporting!

**Comment by muhqu** [comment]
@aberezin I've just updated to [iTerm2 3.0.1 beta](http://iterm2.com/downloads.html) and do not have any issues with opening the terminal window. When iTerm is not running already, it get's started and the command gets evaluated. 

The log message you see actually appears because DTerm is checking first for the old `net.sourceforge.iTerm`  and then for the new `com.googlecode.iterm2` app bundle id. But this should not cause any harm...

Are you already using this fork's [latest build](https://github.com/muhqu/dterm/releases/latest) of DTerm?

**Comment by aberezin** [comment]
When I saw the problem, I was using the last release from decimus.net/dterm. I have since forked and build from master head of https://github.com/muhqu/dterm and I dont have problem. So I would consider the issue closed. Thanks for looking at it.

On Jun 9, 2016, at 3:10 PM, Mathias Leppich <notifications@github.com> wrote:

@aberezin I've just updated to iTerm2 3.0.1 beta and do not have any issues with opening the terminal window. When iTerm is not running already, it get's started and the command gets evaluated.

The log message you see actually appears because DTerm is checking first for the old net.sourceforge.iTerm and then for the new com.googlecode.iterm2 app bundle id. But this should not cause any harm...

Are you already using this fork's latest build of DTerm?
